#!/usr/bin/python

# Permissions for google drive
SCOPES = [
    # Gives access to files created by this script
    'https://www.googleapis.com/auth/drive.file'
]

# Path to a credentials.json file on a hard drive (generated by google)
CREDENTIALS = 'credentials.json'

# Path to a token.json file which is used for saving authentication token for future runs
TOKEN = 'token.json'

# List containing tuples with either relative or absolute path to a file
# (can contain patterns according to the rules used by UNIX shell) and directory id
# Use 'root' for top directory
BACKUPS = [('/example/path/to/example/file', 'invalidDirId'),
           ('/example/path/to/example/file2', 'invalidDirId2')]
